services:
  container1:
    build: ./container1
    image: abhisha1thaker/container1
    container_name: container1
    ports:
      - "6000:6000"
    networks:
      - custom-network
    volumes:
      - ./:/etc/data
    depends_on:
      - container2
  
  container2:
    build: ./container2 
    image: abhisha1thaker/container2
    container_name: container2
    networks:
      - custom-network
    volumes:
      - ./:/etc/data

networks:
  custom-network:
    name: app-network
    driver: bridge

